apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prd-ta-projects
commonLabels:
  env: prd
resources:
  - ../../base
replicas:
  - name: ta-frontend
    count: 2
patches:
  - target:
      kind: BackendConfig
      name: ta-frontend
    patch: |-
      - op: replace
        path: /spec/securityPolicy/name
        value: prd-app-security-policy
