apiVersion: v1
kind: ServiceAccount
metadata:
  name: ksa-ta-migrate
  annotations:
    iam.gke.io/gcp-service-account: gsa-ta-migrate@ta-project-and-dot.iam.gserviceaccount.com
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-patcher
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - workflowtaskresults
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-patcher-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-patcher
subjects:
  - kind: ServiceAccount
    name: ksa-ta-migrate
