apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: ta-exec-query-postgres
spec:
  # synchronization:
  #   mutex:
  #     name: ta-exec-query
  ttlStrategy:
    secondsAfterSuccess: 180
    secondsAfterFailure: 3600
  entrypoint: exec-query
  serviceAccountName: ksa-ta-migrate
  templates:
    - name: exec-query
      container:
        image: postgres:14-alpine
        command: ["/bin/sh", "-c"]
        args:
          - |
            set -e;
            echo 'Waiting for database to be ready';
            sleep 30;

            apk add --no-cache curl;

            PGPASSWORD="$POSTGRES_PASSWORD" psql -h "$POSTGRES_HOST" -U "$POSTGRES_USER" -d "$POSTGRES_DB" <<-EOSQL
            CREATE ROLE "$POSTGRES_APP_USER" LOGIN PASSWORD '$POSTGRES_PASSWORD';
            ALTER SCHEMA public OWNER TO "$POSTGRES_USER";
            GRANT ALL ON SCHEMA public TO "$POSTGRES_USER";
            GRANT ALL ON SCHEMA public TO "$POSTGRES_APP_USER";
            GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO "$POSTGRES_APP_USER";
            GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO "$POSTGRES_APP_USER";
            EOSQL

            # なお、一度失敗して巻き戻すマイグレーションは、上記のように常に残しておく。理由は各環境の実行漏れを防止するためである。
            # 失敗したマイグレーションは、上記のように削除しておく。なお、この対応をしないとマイグレーションが進まなくなるので注意。

            echo 'exec-query completed';
            curl -X POST localhost:9091/quitquitquit;
            echo 'Quitquitquit sent';
            exit;
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: ta-envs-frontend
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ta-envs-frontend
                key: POSTGRES_PASSWORD
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: ta-envs-frontend
                key: POSTGRES_DB
          - name: POSTGRES_APP_USER
            valueFrom:
              secretKeyRef:
                name: ta-envs-frontend
                key: POSTGRES_APP_USER
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: ta-envs-frontend
                key: DB_PORT
          - name: DATABASE_ROOT_URL
            valueFrom:
              secretKeyRef:
                name: ta-envs-frontend
                key: DATABASE_ROOT_URL
          - name: POSTGRES_HOST
            valueFrom:
              secretKeyRef:
                name: ta-envs-frontend
                key: POSTGRES_HOST
        lifecycle:
          preStop:
            exec:
              command:
                ["curl", "-X", "POST", "http://localhost:9091/quitquitquit"]
      sidecars:
        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.6.1
          args:
            - "--private-ip"
            - "--structured-logs"
            - "--port=$(DB_PORT)"
            - "--quitquitquit"
            - "$(INSTANCE_CONNECTION_NAME)"
          ports:
            - containerPort: 9091
          envFrom:
            - secretRef:
                name: ta-envs-frontend
          securityContext:
            runAsNonRoot: true
