apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev-ta-projects
commonLabels:
  env: dev
resources:
  - ../../base
replicas:
  - name: ta-backend-ml
    count: 1
patches:
  - target:
      kind: BackendConfig
      name: ta-backend-ml
    patch: |-
      - op: replace
        path: /spec/securityPolicy/name
        value: dev-app-security-policy
