name: build and deploy on gke
on:
  workflow_call:
    inputs:
      WORKLOAD_IDENTITY_PROVIDER:
        description: "The workload identity provider to use"
        required: true
        type: string
      SERVICE_ACCOUNT:
        description: "The service account to use"
        required: true
        type: string
      GAR_LOCATION:
        description: "The location of the Google Artifact Registry"
        required: true
        type: string
      PROJECT_ID:
        description: "The project ID"
        required: true
        type: string
      REPOSITORY:
        description: "The repository name"
        required: true
        type: string
      IMAGE:
        description: "The image name"
        required: true
        type: string
      GKE_ZONE:
        description: "The GKE cluster zone"
        required: true
        type: string
      DEPLOYMENT_NAME:
        description: "The deployment name"
        required: true
        type: string

jobs:
  DockerBuilding:
    timeout-minutes: 30
    runs-on: self-hosted

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: actions/checkout@v3
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          token_format: "access_token"
          workload_identity_provider: ${{ inputs.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ inputs.SERVICE_ACCOUNT }}
          audience: "https://github.com/takaiba"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker configuration
        run: |-
          echo ${{steps.auth.outputs.access_token}} | docker login -u oauth2accesstoken --password-stdin https://${{ inputs.GAR_LOCATION }}-docker.pkg.dev

      - name: Build and push Migrate Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./prisma/Dockerfile
          push: true
          tags: ${{ inputs.GAR_LOCATION }}-docker.pkg.dev/${{ inputs.PROJECT_ID }}/${{ inputs.REPOSITORY }}/${{ inputs.IMAGE }}-migrate:${{ github.sha }}
          cache-from: type=registry,ref=${{ inputs.GAR_LOCATION }}-docker.pkg.dev/${{ inputs.PROJECT_ID }}/${{ inputs.REPOSITORY }}/${{ inputs.IMAGE }}-migrate-cache:latest
          cache-to: type=registry,ref=${{ inputs.GAR_LOCATION }}-docker.pkg.dev/${{ inputs.PROJECT_ID }}/${{ inputs.REPOSITORY }}/${{ inputs.IMAGE }}-migrate-cache:latest,mode=max

      - name: Build and push App Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ inputs.GAR_LOCATION }}-docker.pkg.dev/${{ inputs.PROJECT_ID }}/${{ inputs.REPOSITORY }}/${{ inputs.IMAGE }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ inputs.GAR_LOCATION }}-docker.pkg.dev/${{ inputs.PROJECT_ID }}/${{ inputs.REPOSITORY }}/${{ inputs.IMAGE }}-cache:latest
          cache-to: type=registry,ref=${{ inputs.GAR_LOCATION }}-docker.pkg.dev/${{ inputs.PROJECT_ID }}/${{ inputs.REPOSITORY }}/${{ inputs.IMAGE }}-cache:latest,mode=max
