name: docker-build-push [prd]
on:
  push:
    branches:
      - deploy/prd

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      PROJECT_ID: ta-project-and-dot
      GAR_LOCATION: asia-northeast1
      GKE_ZONE: asia-northeast1-a
      DEPLOYMENT_NAME: ta-frontend
      REPOSITORY: common-repository
      IMAGE: ta-frontend
      SERVICE_ACCOUNT: workload-identity-github-sa@ta-project-and-dot.iam.gserviceaccount.com
      WORKLOAD_IDENTITY_PROVIDER: projects/794880215231/locations/global/workloadIdentityPools/common-github-pool/providers/common-github-pool-provider

  ta-frontend:
    uses: ./.github/workflows/deploy.yml
    needs: build
    with:
      PROJECT_ID: ta-project-and-dot
      GAR_LOCATION: asia-northeast1
      GKE_CLUSTER: ta-cluster-202308261708
      GKE_ZONE: asia-northeast1-a
      NAMESPACE: prd-ta-projects
      DEPLOY_ENV: prd
      DEPLOYMENT_NAME: ta-frontend
      REPOSITORY: common-repository
      IMAGE: ta-frontend
      SERVICE_ACCOUNT: workload-identity-github-sa@ta-project-and-dot.iam.gserviceaccount.com
      WORKLOAD_IDENTITY_PROVIDER: projects/794880215231/locations/global/workloadIdentityPools/common-github-pool/providers/common-github-pool-provider
