repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: check-json
    - id: pretty-format-json
      exclude: |
            (?x)^(
              .*service_account_credentials.json$|
            )$

      args:
        - "--autofix"
        - "--indent=4"
        - "--no-sort-keys"
    - id: end-of-file-fixer
    - id: trailing-whitespace
      exclude: |
            (?x)^(
              .*prompts.py$|
            )$
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.4.8
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.10.0
  hooks:
  -   id: mypy
- repo: https://github.com/crate-ci/typos
  rev: v1.22.4
  hooks:
    - id: typos
