#!/bin/bash

psql -h localhost -U $POSTGRES_USER -d $POSTGRES_DB <<-EOSQL
    CREATE ROLE $POSTGRES_APP_USER LOGIN PASSWORD '$POSTGRES_PASSWORD';
    ALTER SCHEMA public OWNER TO $POSTGRES_USER;
    GRANT ALL ON SCHEMA public TO $POSTGRES_USER;
    GRANT ALL ON SCHEMA public TO $POSTGRES_APP_USER;
    GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO $POSTGRES_APP_USER;
    GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO $POSTGRES_APP_USER;
EOSQL