name: build and deploy on gke
on:
  workflow_call:
    inputs:
      WORKLOAD_IDENTITY_PROVIDER:
        description: "The workload identity provider to use"
        required: true
        type: string
      SERVICE_ACCOUNT:
        description: "The service account to use"
        required: true
        type: string
      GAR_LOCATION:
        description: "The location of the Google Artifact Registry"
        required: true
        type: string
      PROJECT_ID:
        description: "The project ID"
        required: true
        type: string
      REPOSITORY:
        description: "The repository name"
        required: true
        type: string
      IMAGE:
        description: "The image name"
        required: true
        type: string
      GKE_CLUSTER:
        description: "The GKE cluster name"
        required: true
        type: string
      GKE_ZONE:
        description: "The GKE cluster zone"
        required: true
        type: string
      DEPLOY_ENV:
        description: "The deployment environment"
        required: true
        type: string
      DEPLOYMENT_NAME:
        description: "The deployment name"
        required: true
        type: string
      NAMESPACE:
        description: "The namespace"
        required: true
        type: string
      DEPLOY_DIRECTORY:
        description: "The directory to deploy"
        required: true
        type: string

jobs:
  DockerBuilding:
    timeout-minutes: 30
    runs-on: self-hosted

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: actions/checkout@v3
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          token_format: "access_token"
          workload_identity_provider: ${{ inputs.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ inputs.SERVICE_ACCOUNT }}
          audience: "https://github.com/takaiba"

      - name: Docker configuration
        run: |-
          echo ${{steps.auth.outputs.access_token}} | docker login -u oauth2accesstoken --password-stdin https://${{ inputs.GAR_LOCATION }}-docker.pkg.dev

      - name: Set up GKE credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ inputs.GKE_CLUSTER }}
          location: ${{ inputs.GKE_ZONE }}

      # セットアップ Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # ビルドとプッシュを一つのステップで実行（キャッシュを有効化）
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ${{ inputs.DEPLOY_DIRECTORY }}
          file: ${{ inputs.DEPLOY_DIRECTORY }}/Dockerfile
          push: true
          tags: ${{ inputs.GAR_LOCATION }}-docker.pkg.dev/${{ inputs.PROJECT_ID }}/${{ inputs.REPOSITORY }}/${{ inputs.IMAGE }}:${{ github.sha }}
          build-args: |
            GITHUB_SHA=${{ github.sha }}
            GITHUB_REF=${{ github.ref }}
          cache-from: type=registry,ref=${{ inputs.GAR_LOCATION }}-docker.pkg.dev/${{ inputs.PROJECT_ID }}/${{ inputs.REPOSITORY }}/${{ inputs.IMAGE }}:buildcache
          cache-to: type=registry,ref=${{ inputs.GAR_LOCATION }}-docker.pkg.dev/${{ inputs.PROJECT_ID }}/${{ inputs.REPOSITORY }}/${{ inputs.IMAGE }}:buildcache,mode=max
