name: build and deploy on gke
on:
  workflow_call:
    inputs:
      DEPLOY_ENV:
        required: true
        type: string
      DEPLOYMENT_NAME:
        required: true
        type: string
      REPOSITORY:
        required: true
        type: string
      IMAGE:
        required: true
        type: string
      MONOREPO_PATH:
        required: true
        type: string
      NAMESPACE:
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
      SSH_HOST:
        required: true
      SSH_USERNAME:
        required: true
      SSH_KEY:
        required: true

jobs:
  DockerBuilding:
    timeout-minutes: 30
    runs-on: self-hosted
    steps:
      # リポジトリをチェックアウト
      - name: Check out the repo
        uses: actions/checkout@v2

      # Docker Buildx をセットアップ
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      # Docker Hub にログイン
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Docker イメージをビルドしてプッシュ
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./
          push: true
          tags: ${{ inputs.REPOSITORY }}/${{ inputs.IMAGE }}:${{ github.sha }}

      # リポジトリを再度チェックアウト
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # リポジトリファイルをリモートにコピー
      - name: "Copying repository files to remote"
        uses: milanmk/actions-file-deployer@master
        with:
          remote-protocol: "sftp"
          remote-host: ${{ secrets.SSH_HOST }}
          remote-user: ${{ secrets.SSH_USERNAME }}
          ssh-private-key: ${{ secrets.SSH_KEY }}
          local-path: ./
          remote-path: "/root/deployment/${{ github.repository }}"
          sync: full

      # Kustomize をセットアップしてデプロイ
      - name: Set up Kustomize and Deploy
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          privateKey: ${{ secrets.SSH_KEY }}
          command: |
            cd /root/deployment/${{ github.repository }}/k8s/overlayes/${{inputs.DEPLOY_ENV}}
            [ -d "kustomize" ] && echo 1 || curl -sfL https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv5.0.3/kustomize_v5.0.3_linux_amd64.tar.gz | tar xz && chmod u+x ./kustomize

            ./kustomize edit set image image=${{ inputs.REPOSITORY }}/${{ inputs.IMAGE }}:${{ github.sha }}
            # ジョブが存在するときは待機する
            kubectl wait --for=condition=complete job/${{ inputs.DEPLOYMENT_NAME }} -n ${{ inputs.NAMESPACE }} || true
            ./kustomize build . | kubectl apply -f -
            kubectl wait --for=condition=complete job/${{ inputs.DEPLOYMENT_NAME }} -n ${{ inputs.NAMESPACE }}
            kubectl logs job/${{ inputs.DEPLOYMENT_NAME }} -n ${{ inputs.NAMESPACE }}
            kubectl get jobs -o wide -n ${{ inputs.NAMESPACE }}
