apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: ta-migrate
spec:
  # synchronization:
  #   mutex:
  #     name: ta-migrate
  ttlStrategy:
    secondsAfterSuccess: 180
    secondsAfterFailure: 3600
  entrypoint: migrate
  serviceAccountName: ksa-ta-migrate
  templates:
    - name: migrate
      container:
        image: image
        command: [
            "/bin/bash",
            "-c",
            "
            set -e;
            echo 'Waiting for database to be ready';
            sleep 30;
            echo 'Database ready, starting migration';
            npx prisma migrate deploy;
            echo 'Migrate completed';
            curl -X POST localhost:9091/quitquitquit;
            echo 'Quitquitquit sent';
            exit;
            ",
          ]
        args: []
        env:
          - name: DATABASE_ROOT_URL
            valueFrom:
              secretKeyRef:
                name: ta-envs-frontend
                key: DATABASE_ROOT_URL
        lifecycle:
          preStop:
            exec:
              command:
                ["curl", "-X", "POST", "http://localhost:9091/quitquitquit"]
      sidecars:
        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.6.1
          args:
            - "--private-ip"
            - "--structured-logs"
            - "--port=$(DB_PORT)"
            - "--quitquitquit"
            - "$(INSTANCE_CONNECTION_NAME)"
          ports:
            - containerPort: 9091
          envFrom:
            - secretRef:
                name: ta-envs-frontend
          securityContext:
            runAsNonRoot: true
